---
mode: dev
ssl: 'false'
host: http://localhost:8090
feeder: AAF
importDirectory: /home/wse/aaf
logDirectory: /tmp/log
httpProxy: 'true'
applycommunication: 'true'
webdavCredential: 'false'
webdavHost: localhost
webdavUsername: 
webdavPassword:
webdavInsecure: 
exporter: ELIOT
exportPath: /tmp
exportDestination: 
senderEmail: ne-pas-repondre@cg77.fr
neo4jAAFPlugin: 'false'
neo4jUri: http://neo4j:7474
logoutCallback: 
dbName: one_gridfs
mongoHost: mongo
mongoPort: 27017
sqlUrl: jdbc:postgresql://postgres:5432/ong?stringtype=unspecified
sqlUsername: web-education
sqlPassword: We_1234
fsStoragePath: /srv/storage/
patternDefaultRegisteredService: "^(http|https):\\/\\/.*"
patternUidRegisteredService: 
patternUniversalisRegisteredService: 
patternLeSiteTvRegisteredService: 
patternKneRegisteredService: 
patternPronoteRegisteredService: 
patternEliotRegisteredService: 
patternWebclasseursRegisteredService: 
patternEducagriRegisteredService: "^(http|https):\\/\\/educagrinet\\\\.educagri\\\\.fr\\/.*"
eliotExportedDelay: 600000
eliotAppliCode: 
eliotUri: 
eliotSaasUri: 
themes: '{"_id": "default","displayName": "default","path": "/assets/themes/leo/default/"},{"_id": "dyslexic","displayName": "dyslexic","path": "/assets/themes/leo/dyslexic/"}'
resourcesApplications: ["workspace", "blog", "actualites", "wiki", "pages", "poll", "timelinegenerator", "rack", "collaborativewall"]
widgets: '{"name": "recorder", "path": "/public/template/record-me.html", "js": "/public/js/record-me.js"}, {"name": "calendar","path": "/public/template/calendar.html","js": "/public/js/calendar.js"},{"name": "notes","path": "/public/template/notes.html","js": "/public/js/notes.js"},{"name": "actualites","path": "/actualites/public/template/last-infos-widget.html","js": "/actualites/public/js/last-infos-widget.js","i18n": "/actualites/i18n"},{"name": "rss","path": "/rss/public/template/rss-widget.html","js": "/rss/public/js/rss-widget.js","i18n": "/rss/i18n"}'
defaultCommunicationRules: '{"Structure-Personnel" : { "users" : "BOTH", "communiqueWith" : ["Structure-Teacher", "Structure-Relative", "Structure-Student"]},"Structure-Teacher" : { "users" : "BOTH", "communiqueWith" : ["Structure-Personnel", "Structure-Relative", "Structure-Student"]},"Structure-Student" : {"users" : "OUTGOING"},"Structure-Relative" : {"users" : "OUTGOING"},"Class-Personnel" : {"users" : "OUTGOING"},"Class-Teacher" : {"users" : "OUTGOING"},"Class-Student" : { "users" : "BOTH", "communiqueWith" : ["Class-Teacher"]},"Class-Relative" : { "users" : "BOTH", "Relative-Student" : "BOTH", "communiqueWith" : ["Class-Teacher"]}}'
skin: 'raw'
assetsPath: /srv/springboard
entcoreVersion: '3.1.13'
swiftUri: 
swiftContainer: 
swiftUser: 
swiftKey: 
passwordRegex: .*
neo4jPlugin: 'false'
activateEscalation: 'false'
activationAutoLogin: 'false'
skins: '{"localhost:8090":"cg77", "192.168.99.100:8090":"cg77"}'
xitiSwitch: 
sharedConf: 
authMandatoryFields: '{}'
patternProEPSRegisteredService: 
signKey: 
samlMetadataFolder: 
samlPrivateKey: 
federationLoginUri: 
federationCallBackParam: 
samlServicesProviders: '{}'
autoExport: 'false'
federatedAddress: '{}'
activationWelcomeMessage: 'false'
teacherForgotPasswordEmail: 'false'
createdUserEmail: 'false'
classDefaultRoles: 'false'
cnsConfig: '{}'
patternEduMediaRegisteredService: 
patternGepiRegisteredService: 
patternMSELRegisteredService: 
patternGRRRegisteredService: 
samlIssuer: 
samlSLO: 'false'
emailConfig:
flatFsStorage: 'false'
smsProviders: '{}'
cluster: 'false'
neo4jSlaveReadOnly: 'false'
csrfToken: 'true'
wizardFeeders: '["CSV"]'
casExternalLoginUri:
etherpadUrl: http://ns3027012.ip-51-255-66.eu:8092
etherpadApiKey: 62cc0a3507b8ab13b3f641a07f93138d59880071af0e10f84d0f9e1937c76e97
# E.g. your domain name
#modowner: fr.wseduc

#modname: cg77

# Your module version
#version: 3.1-SNAPSHOT

# The test timeout in seconds
testtimeout: 300
# Set to 'true' if you want module dependencies to be pulled in and nested inside the module itself
pullInDeps: 'false'

# Set to 'true' if you want the build to output a jar as well as a module zip file
produceJar: 'false'

# The version of Groovy language to compile against (if you are using Groovy compiled verticles or VertxTests)
groovyLangModVersion: 2.0.0-final

# The version of Groovy to use (if you are using Groovy)
groovyVersion: 2.1.1

# provided lib
gradleVersion: 1.6
vertxVersion: 2.0.0-final
toolsVersion: 2.0.0-final
junitVersion: 4.10
processorVersion: 1.0.0

# compile lib
entCoreVersion: 3.1.13
blogVersion: 2.1.3
actualitesVersion: 1.1.2
forumVersion: 1.1.3
rbsVersion: 1.1.1
wikiVersion: 1.1.2
rssVersion: 1.1.0
pagesVersion: 1.1.3
communityVersion: 1.1.0
rackVersion: 1.1.1
bookmarkVersion: 1.1.0
springboardPluginVersion: 2.1.0
calendarVersion: 1.1.1
collaborativewallVersion: 1.1.2
mindmapVersion: 1.1.2
eliotVersion: 1.1.0
collaborativeEditorVersion: 1.1.1
timelinegeneratorVersion: 1.1.4
fakeSSOVersion: 1.1.0
xitiVersion: 1.1.0
statisticsVersion: 1.1.0
homeworksVersion: 1.1.2
scrapbookVersion: 1.1.2
cnsVersion: 1.1.0
exercizerVersion: 2.0.3
schoolbookVersion: 1.1.2
vieScolaireVersion: 1.1.3
competencesVersion: 1.1.3
presencesVersion: 1.0.0
edtVersion: 1.1.0
diaryVersion: 2.2.0
applicationHelpVersion: 3.1.1
...